### ISSUE TITLE
UnEndorse: PogChamp

### ISSUE THREAD

**Issue by peopledrivemecrazy** [sw-yx/sw-yx#13]
> PogChamp

**Comment by sw-yx** [comment]
i dont understand this one lol

**Comment by peopledrivemecrazy** [comment]
A little background this is one of the most used twitch emote.

![image](https://user-images.githubusercontent.com/3922469/87314927-78e45f00-c541-11ea-993f-6fab1a2385da.png)



but now i am sad. ```Pepehands```
![Pepehands](https://user-images.githubusercontent.com/3922469/87315630-40915080-c542-11ea-86d0-cbb1b1ce1431.png)


ps. You have a great profile page.

**Comment by sw-yx** [comment]
haha thx!
