### ISSUE TITLE
Endorse: Typescript

### ISSUE THREAD

**Issue by juanfrank77** [sw-yx/sw-yx#17]
I learned several things of Typescript from the stuff you made and your talk of Fullstack React + GraphQL made me not _dislike_ Typescript that much and see how having a full typed frontend can be useful for a typed backend (still think there could be better alternatives to TS but 🤷‍♂️)

**Comment by sw-yx** [comment]
thank you! this is a duplicate - do u mind liking this one? https://github.com/sw-yx/sw-yx/issues/14

**Comment by sw-yx** [comment]
and honestly that talk was NOT my best... haha.. i only rehearsed 1 time and screwed up a lot. so really appreciate that you said nice things about it. I WILL make the talk better, i promise.

**Comment by juanfrank77** [comment]
> 
> 
> and honestly that talk was NOT my best... haha.. i only rehearsed 1 time and screwed up a lot. 

Haha we're always our worst critics 😅
My sister is a singer & musician and most of the times she has told them that she screwed up and probably sounded horrible and I'm like "no one really noticed, they actually enjoyed hearing you"
