### ISSUE TITLE
HOW TO ENDORS

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/sw-yx#8]
Henlo I need your endorsment to valid my skills for the business jobbing.

to endors plz hav issue with "ENDORSE: " and then like and subscribe and smashh bell

thank yo for ted talk coming

**Comment by koolamusic** [comment]
```
Hello, I need your endorsment to validate my skills for job opportunities.

To endorse please create issue with "ENDORSE: " and then like, subscribe and smash bell
Thank you for listening to my Ted Talk. :smile: 
```

This is a suggested typo fix/replacement

**Comment by sw-yx** [comment]
its not serious :)
